# Generated by Django 6.1.1 on 2026-09-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_document_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencechain",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
