# Generated by Django 6.1.1 on 2026-09-04 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_evidencechain_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="FIR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fir_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fir_record",
                        to="api.case",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fir_details",
                        to="api.document",
                    ),
                ),
            ],
        ),
    ]
