# Generated by Django 6.1 on 2026-09-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_document_deleted_at_document_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
