# Generated by Django 6.1 on 2026-09-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_case_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='verification_status',
            field=models.CharField(blank=True, default='PENDING_VERIFICATION', max_length=50, null=True),
        ),
    ]
